<a href="https://colab.research.google.com/github/cjfghk5697/Numpy_practice/blob/main/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>넘파이 문제 풀기(basicfunction1 보면 풀수 있음)</h1>
1. 넘파이 (3,3) 사이즈 배열을 만드시오
<br>2. 넘파이 (4,4)를 0과 1로 채워진 float, int 형을 만드시오
<br>3. 넘파이 표준편차 1, 평균이 0인 즉 정규분포표에서 (4,4) 사이즈 배열을 만드시오
<br>4. (1,2,3,4)인 1차원 배열 넘파이를 ((1,2) (3,4))2차원으로 바꾸시오
<br>5. 넘파이 배열 (1,2,3,4)와 (5,6,7,8)을 합치시오
<br>6. 5번을 세로로 합치시오
<br>7. 6번을 나눠서 원본형태로 돌려놓으시오

In [2]:
import numpy as np

#1번 문제
array=np.arange(9).reshape(3,3)
print(array)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


<h1>해석</h1>
np.arange(9).reshape(3,3)을 해체(해체철학 아님 ㅋㅋ)해보겠다.
일단 np는 넘파이를 가져온거다. 그리고 arange(9)는 0부터 9까지 하나하나 수를 만들어 array배열에 넣어준다. 그다음 reshape 함수는 0부터 9까지 있는 배열을 3*3 배열로 만들어준다. 정말 간단한 코드이다. 하지만 넘파이가 없다면 진짜 개더럽게 하나하나 만들어야한다. 

In [ ]:
#2번 문제
array=np.zeros((4,4),dtype=float)
print(array)
array=np.ones((4,4),dtype=int)
print(array)
array=np.ones((4,4),dtype=str)
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


<h1>해석</h1>
zeros는 0을 ones는 1을 넣어준다. dtype은 데이터 타입을 정해준다. 자세히 보면 float 형  0뒤에 .이 있다. 반면 int형은 숫자 그대로 보여준다. 그리고 추가적으로 str을 넣었는데 str에는 ' '있는 걸 확인 할 수 있다.

In [ ]:
#3번 답
array=np.random.normal(0,1,(4,4))
print(array)

#추가 문제
array=np.random.randint(0,9,(4,4))
print(array)

[[-0.24670542  1.96642943  0.50971632 -1.31768666]
 [ 0.03931815 -1.10318917  0.4536639   0.72255716]
 [ 1.875774   -0.69086223  0.25097857  1.4794537 ]
 [-2.1785534  -0.40411734  1.12014216  2.25787528]]
[[2 2 8 6]
 [3 1 7 1]
 [0 1 0 8]
 [3 3 8 4]]


<h1>해석</h1>
2번은 random함수로 정규분포 내에 있는 0~1의 값을 4*4크기 배열로 가져와 만든 것이다. 여기서 필자가 주목한 부분은 1번 문제에서 우리는 배열 크기에 맞춰 arange()로 수를 생성했다. 하지만 여기서는 random이기 때문에 그냥 크기만 써주면 자동으로 하나하나 만들어준다. normal는 정규분포 형식으로 평균 0, 표준편차 1로 만들어준다.

<br><br>
추가 문제로 random.radint를 넣었는데 이거는 normal 없이 그냥 랜덤 그자체다. 둘다 알아둬야한다.

In [ ]:
#4번 문제
array=np.array([1,2,3,4])
array=array.reshape((2,2))
print(array)

[[1 2]
 [3 4]]


<h1>해석</h1>
(1,2,3,4) 모습인 배열을 reshape((2,2))를 이용해 2차원 배열로 만들었다. 중요한점은 reshape()안에 괄호를 또 넣어야한다는 점이다.

In [ ]:
#5번 문제
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
array=np.concatenate([array1,array2])
print(array)


[1 2 3 4 5 6 7 8]


<h1>해석</h1>
array1,array2를 concatenate함수를 이용해 배열을 합쳤다.

In [14]:
#6번 문제
array1=np.arange(4).reshape(1,4)
array2=np.arange(8).reshape(2,4)

print(array1)
print(array2)

array=np.concatenate([array1,array2],axis=0)
print(array)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


<h1>해석</h1>
axis를 이용해 세로, 가로 합치는 것을 활용 할 수 있다. 

In [18]:
array3,array4=np.split(array,2,axis=1)
print(array3,"\n",array4)



[[0 1]
 [0 1]
 [4 5]] 
 [[2 3]
 [2 3]
 [6 7]]


<h1>해석</h1>
split으로 2개로 나눴다 가로로
