<a href="https://colab.research.google.com/github/cjfghk5697/Numpy_practice/blob/main/BasicFunction2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#브로드캐스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환
array1=np.arange(4).reshape(2,2)
array2=np.arange(2)

array3=array1+array2

print(array3)

[[0 2]
 [2 4]]


In [3]:
#세로축으로 
array4=np.arange(0,8).reshape(2,4)
array5=np.arange(0,8).reshape(2,4)
array6=np.concatenate([array4,array5],axis=0)

print(array6)
#array6에 4x1크기 더하기 여기서 브로드캐스트 확인가능
array5=np.arange(0,4).reshape(4,1)

print(array5+array6)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [8]:
#마스킹 연산: 각원소를 체크
array7=np.arange(16).reshape(4,4)
print(array7)

array8=array7<10
print(array8)
#True 값들 100으로 바꾸기
array7[array8]=100
print(array7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [11]:
#넘파이 집계함수 
array9=np.arange(16).reshape(4,4)

print("최대값",np.max(array9))
print("최소값",np.min(array9))
print("총합",np.sum(array9))
print("평균",np.mean(array9))

최대값 15
최소값 0
총합 120
평균 7.5


In [12]:
#넘파이 집계함수 (세로축으로 하기)

print("최대값",np.max(array9, axis=0))
print("최소값",np.min(array9, axis=0))
print("총합",np.sum(array9, axis=0))
print("평균",np.mean(array9, axis=0))

최대값 [12 13 14 15]
최소값 [0 1 2 3]
총합 [24 28 32 36]
평균 [6. 7. 8. 9.]
