<a href="https://colab.research.google.com/github/cjfghk5697/Numpy_practice/blob/main/practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>넘파이 문제 풀기(basicfunction3 보면 풀수 있음)</h1>
1. numpy 저장과 불러오기
<br>2. numpy 정렬
<br>3. 균일한 간격으로 데이터 생성
<br>4. 난수의 재연(실행마다 결과 동일)
<br>5.numpy 배열 객체 복사
<br>6. numpy 중복 값 삭제


In [4]:
#1번
import numpy as np
array=np.arange(6)
np.save('save.npy',array)
array1=np.arange(3)
np.savez('saved.npz',array1=array1,array=array)

data=np.load('saved.npz')
print(data)
result1=data['array1']
result2=data['array']
print(result1)
print(result2)

[0 1 2]
[0 1 2 3 4 5]


<h1>해석</h1>
save, 파일 형식 npy-배열 하나<br>
savez, 파일 형식 npz-배열 여러개
<br>load함수로 배열을 가져올 수 있다.


In [5]:
#2번
array= np.array([5,9,10,3,1])
array.sort()
print(array)
print(array[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]


<h1>해석</h1>
sort()는 정렬을 해주고 오름차순이다. 원래는 reverse=true로 내림차순이 가능하다. 하지만 array[::-1]을 이용해서 내림차순도 가능하다.

In [7]:
#3번
array=np.linspace(0,10,5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


<h1>해석</h1>
arange함수는 0부터 1씩 증가하여 배열을 채운다. 하지만 linspace는 쪼개어 배열을 채운다는 점에서 차이가 있다. 

In [8]:
#4번
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

[[4 9 6]
 [3 3 7]]


<h1>해석</h1>
seed로 언제나 결과가 똑같이 나온다.

In [9]:
#5번

#numpy 배열 객체 복사
array=np.arange(0,10)
array1=array
array1[0]=99
print(array)
#위처럼 쓰면 array6과 array7 주소 같아서 하나라도 바뀌면 동일하게 바뀜
array=np.arange(0,10)
array1=array.copy()
array1[0]=99
print(array)

[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


<h1>해석</h1>
그냥 array1=array하면 두개의 주소가 같아서 하나라도 바뀌면 동시에 바뀐다. 하지만 .copy()함수를 이용하면 다르게 바뀐다. 