<a href="https://colab.research.google.com/github/cjfghk5697/Numpy_practice/blob/main/BasicFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#0부터 3까지의 배열 만들기
array=np.arange(4)
print(array)

[0 1 2 3]


In [2]:
#4*4 배열, 0으로 채워지고 타입은 float
array2= np.zeros((4,4),dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# 1로 채움
array3= np.ones((4,4),dtype=str)
print(array3)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [4]:
#0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4=np.random.randint(0,10,(3,3))
print(array4)

[[1 6 2]
 [2 8 9]
 [8 5 5]]


In [5]:
#정규분포 평균 0 표준편차 1
array5=np.random.normal(0,1,(3,3))
print(array5)

[[-0.85132267  1.07792536  0.77658765]
 [-0.45724964 -1.10884778 -0.02202763]
 [ 1.1057255  -1.92534337  1.31532172]]


In [6]:
#배열 합치기
array6=np.array([1,2,3])
array7=np.array([4,5,6])
array8=np.concatenate([array6,array7])

print(array8.shape)
print(array8)

(6,)
[1 2 3 4 5 6]


In [7]:
#배열 형태 바꾸기
array9=np.array([1,2,3,4])
array10=array9.reshape((2,2))
print(array10)

[[1 2]
 [3 4]]


In [8]:
#배열 세로 축으로 합치기, axis=0(세로)
array11=np.arange(4).reshape(1,4)
array12=np.arange(8).reshape(2,4)

print(array11)
print(array12)

array13=np.concatenate([array11,array12],axis=0)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


In [9]:
#배열 나누기
array14=np.arange(8).reshape(2,4)
left,right=np.split(array14,[2],axis=1)
print(left.shape)
print(right.shape)
print(left)
print(right)

(2, 2)
(2, 2)
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
