<a href="https://colab.research.google.com/github/cjfghk5697/Numpy_practice/blob/main/BasicFunction3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy 저장과 불러오기 ex) seave_.npy

import numpy as np

#e단일 객체 저장 및 불러오기
array=np.arange(0,10)
np.save('saved.npy',array)

result=np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#복수 객체 저장 및 불러오기

array1=np.arange(0,10)
array2=np.arange(10,20)
np.savez('saved.npz', array1=array1,array2=array2)

data=np.load('saved.npz')
result1= data['array1']
result2=data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [5]:
#numpy원소 오름차순 정렬

array3= np.array([5,9,10,3,1])
array3.sort()
print(array3)
#nummpy 내림차순
print(array3[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]


In [6]:
#열기준 정렬
array4=np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array4)
array4.sort(axis=0)
print(array4)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [8]:
# 균일한 간격으로 데이터 생성
array5=np.linspace(0,10,5)
print(array5)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
#난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

[[4 9 6]
 [3 3 7]]


In [15]:
#numpy 배열 객체 복사
array6=np.arange(0,10)
array7=array6
array7[0]=99
print(array6)
#위처럼 쓰면 array6과 array7 주소 같아서 하나라도 바뀌면 동일하게 바뀜
array6=np.arange(0,10)
array7=array6.copy()
array7[0]=99
print(array6)

[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
#numpy 중복 값 삭제
array10=np.array([1,1,2,2,2,3,3,4])
print(np.unique(array10))

[1 2 3 4]
